spring.application.name=mastersys

sping.datasource.url=jdbc:postgresql://localhost:5432/mastersys
spring.datasource.username=postgres
spring.datasource.password=*****

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration